// English translations of all content arrays.
// Mirrors the shape of the Russian arrays in main.ts.

export const commandsEn = [
  {
    command: 'git --version',
    meaning: 'Checks whether Git is installed and which version you are using.',
    when: 'Right at the start, when setting up your machine.',
    tip: 'If the command is not found, install Git for Windows and restart VS Code.',
    stage: 'start',
  },
  {
    command: 'git config --global user.name "Ivan Petrov"',
    meaning: 'Records the author name that will be visible in your commits.',
    when: 'Once on a new computer.',
    tip: 'Use your real name or the work nickname your team uses.',
    stage: 'start',
  },
  {
    command: 'git config --global user.email "ivan@example.com"',
    meaning: 'Records the email of the commit author.',
    when: 'Once, alongside user.name.',
    tip: 'Best to use the email tied to your GitHub account so commits show up in your profile.',
    stage: 'start',
  },
  {
    command: 'git clone https://github.com/org/project.git',
    meaning: 'Downloads a remote repository onto your computer.',
    when: 'When you connect to a project for the first time.',
    tip: 'In VS Code you can do the same via Command Palette: Git: Clone.',
    stage: 'start',
  },
  {
    command: 'git status',
    meaning: 'Shows the current branch, changed files and what is already staged.',
    when: 'Before every commit, pull, merge or branch switch.',
    tip: 'The safest habit in Git: status first, action second.',
    stage: 'daily',
  },
  {
    command: 'git pull --ff-only',
    meaning: 'Fetches fresh changes from the remote branch without creating a merge commit.',
    when: 'At the start of the day and before creating a new branch.',
    tip: 'If a fast-forward is impossible, Git stops so you can sort it out instead of mixing history automatically.',
    stage: 'daily',
  },
  {
    command: 'git checkout -b feature/login-form',
    meaning: 'Creates a new branch and switches you to it immediately.',
    when: 'Before starting a separate task.',
    tip: 'Keep branch names short: feature, fix, chore plus the gist of the task.',
    stage: 'branch',
  },
  {
    command: 'git add src/LoginForm.tsx',
    meaning: 'Adds the selected file to the upcoming commit.',
    when: 'When part of your changes is ready to be recorded.',
    tip: 'You don\u2019t have to add everything at once. Small, logical commits are easier to review.',
    stage: 'daily',
  },
  {
    command: 'git commit -m "Add login form validation"',
    meaning: 'Captures a snapshot of the staged changes with a clear description.',
    when: 'When a small, logical step is done.',
    tip: 'Write the message as if you were explaining the change to a colleague.',
    stage: 'daily',
  },
  {
    command: 'git push -u origin feature/login-form',
    meaning: 'Sends the branch to GitHub and links your local branch to the remote one.',
    when: 'Before opening a pull request or to back up your work on GitHub.',
    tip: 'After the first push for a branch, plain git push is usually enough.',
    stage: 'pr',
  },
  {
    command: 'gh pr create --fill --base main',
    meaning: 'Opens a pull request via GitHub CLI, filling title and body from your commits.',
    when: 'When the task is ready for review.',
    tip: 'If GitHub CLI is not installed, open the PR via the GitHub site or the GitHub Pull Requests extension.',
    stage: 'pr',
  },
  {
    command: 'git fetch origin',
    meaning: 'Updates information about branches on GitHub without changing your files.',
    when: 'Before comparing branches, rebasing or checking out someone else\u2019s branch.',
    tip: 'Fetch is safer than pull when you only want to see what changed remotely.',
    stage: 'daily',
  },
  {
    command: 'git rebase origin/main',
    meaning: 'Replays your commits on top of the latest main.',
    when: 'When the PR has fallen behind the main branch and your team prefers linear history.',
    tip: 'Don\u2019t rebase a published shared branch without coordinating with the team.',
    stage: 'pr',
  },
  {
    command: 'git stash push -m "wip before hotfix"',
    meaning: 'Temporarily stashes unfinished changes.',
    when: 'When you need to switch to another task urgently.',
    tip: 'When you come back, use git stash pop, but check git status first.',
    stage: 'rescue',
  },
  {
    command: 'git log --oneline --graph --decorate --all',
    meaning: 'Shows a compact map of branch and commit history.',
    when: 'When you need to understand where your branch sits relative to main.',
    tip: 'If the graph is hard to read, install Git Graph or GitLens in VS Code.',
    stage: 'history',
  },
  {
    command: 'git switch main',
    meaning: 'A modern, safer replacement for git checkout to switch branches.',
    when: 'Whenever you need to move to another existing branch.',
    tip: 'git switch -c new-branch creates a branch and switches to it in one step.',
    stage: 'branch',
  },
  {
    command: 'git restore --staged file.ts',
    meaning: 'Removes the file from the staging area but keeps your changes on disk.',
    when: 'When you accidentally git add the wrong file.',
    tip: 'git restore file.ts without --staged reverts the file to the last commit.',
    stage: 'daily',
  },
  {
    command: 'git diff --staged',
    meaning: 'Shows exactly what will go into your next commit.',
    when: 'Before every git commit, to make sure nothing extra slips in.',
    tip: 'In VS Code the same diff is available in the Source Control tab when you click a file.',
    stage: 'daily',
  },
  {
    command: 'git commit --amend --no-edit',
    meaning: 'Adds staged changes to the last commit without changing the message.',
    when: 'When you forgot to include something in the commit you just made.',
    tip: 'Don\u2019t amend a commit that has already been published if others rely on it.',
    stage: 'rescue',
  },
  {
    command: 'git cherry-pick a1b2c3d',
    meaning: 'Brings a single specific commit from another branch into the current one.',
    when: 'When you need to port a targeted fix between release branches.',
    tip: 'If a conflict appears, resolve it and use git cherry-pick --continue.',
    stage: 'rescue',
  },
  {
    command: 'git revert a1b2c3d',
    meaning: 'Creates a new commit that undoes the changes from the specified commit.',
    when: 'When a bad commit is already on main and rewriting history is not allowed.',
    tip: 'Safe for shared branches, unlike git reset.',
    stage: 'rescue',
  },
  {
    command: 'git reset --soft HEAD~1',
    meaning: 'Undoes the last commit, keeping the changes staged.',
    when: 'When you need to rewrite the message or split the commit into several.',
    tip: '--mixed (default) unstages, --hard wipes the changes. Be careful.',
    stage: 'rescue',
  },
  {
    command: 'git reflog',
    meaning: 'Shows every move of HEAD: branches, resets, rebases, checkouts.',
    when: 'When it feels like commits or a branch have "disappeared".',
    tip: 'Using a hash from reflog you can recover almost any state via git reset --hard <hash>.',
    stage: 'rescue',
  },
  {
    command: 'git bisect start && git bisect bad && git bisect good v1.0',
    meaning: 'Uses binary search to find the commit that introduced a bug.',
    when: 'When the bug was definitely fixed in a past version but it is unclear where it broke.',
    tip: 'Git serves you the right commits. When done, run git bisect reset.',
    stage: 'history',
  },
  {
    command: 'git blame src/api.ts',
    meaning: 'Shows who changed each line of a file, and in which commit.',
    when: 'When you need to understand the reason behind a line of code.',
    tip: 'In VS Code, GitLens shows blame as a hint right next to the line.',
    stage: 'history',
  },
  {
    command: 'git tag -a v1.4.0 -m "Release 1.4.0" && git push origin v1.4.0',
    meaning: 'Creates an annotated tag and publishes it to GitHub.',
    when: 'When releasing a version, to pin a specific commit.',
    tip: 'GitHub Releases can be created automatically from tags via GitHub Actions.',
    stage: 'pr',
  },
  {
    command: 'git branch -d feature/login-form',
    meaning: 'Deletes a local branch if it has already been merged.',
    when: 'After the PR is merged and the branch is no longer needed.',
    tip: 'Use -D to delete a branch that has not been merged yet (carefully).',
    stage: 'branch',
  },
  {
    command: 'git push origin --delete feature/login-form',
    meaning: 'Deletes the branch from the remote repository on GitHub.',
    when: 'After merging a PR, if auto-delete branches is not enabled.',
    tip: 'Many teams enable "Automatically delete head branches" in repository settings.',
    stage: 'branch',
  },
  {
    command: 'git remote -v',
    meaning: 'Shows which remote repositories your project is connected to.',
    when: 'When working with a fork and you need to check origin and upstream.',
    tip: 'git remote add upstream <url> connects the original repository to your fork.',
    stage: 'start',
  },
  {
    command: 'git clean -fd',
    meaning: 'Removes untracked files and empty directories.',
    when: 'When experiments leave junk behind in the repository.',
    tip: 'Run git clean -nd first \u2014 it shows what would be deleted without deleting anything.',
    stage: 'rescue',
  },
  {
    command: 'git stash pop',
    meaning: 'Restores the changes from the latest stash and removes it.',
    when: 'When you return to the parked task after a hotfix.',
    tip: 'If there are several stashes, use git stash list and git stash apply stash@{1}.',
    stage: 'rescue',
  },
  {
    command: 'git log -p src/auth.ts',
    meaning: 'Shows the file\u2019s history with all the diffs.',
    when: 'When you need to follow how a specific file evolved.',
    tip: 'Add --follow so Git tracks file renames as well.',
    stage: 'history',
  },
  {
    command: 'gh pr checkout 142',
    meaning: 'Pulls someone else\u2019s pull request into a local branch for review.',
    when: 'When you need to run a colleague\u2019s PR locally and test it.',
    tip: 'The same is available as a single click in the GitHub Pull Requests extension.',
    stage: 'pr',
  },
  {
    command: 'git config --global pull.rebase true',
    meaning: 'Makes rebase the default behavior for git pull.',
    when: 'If your team prefers linear history without merge commits.',
    tip: 'Combine with git config --global rebase.autoStash true for automatic stashing.',
    stage: 'start',
  },
  {
    command: 'git push --force-with-lease',
    meaning: 'A safe force-push: it will not overwrite somebody else\u2019s commits on the branch.',
    when: 'After rebasing or amending a published PR branch.',
    tip: 'Never use plain --force on shared branches like main.',
    stage: 'pr',
  },
  {
    command: 'git fetch --prune',
    meaning: 'Fetches updates from the remote and removes stale remote-tracking branches that no longer exist on GitHub.',
    when: 'Periodically, so the branch list doesn\u2019t accumulate leftovers from merged PRs.',
    tip: 'Set git config --global fetch.prune true \u2014 then prune happens automatically on every fetch/pull.',
    stage: 'daily',
  },
] as const

export const workflowsEn = [
  {
    title: 'A new contributor joins the project',
    role: 'Developer',
    body: 'First they install Git, sign in to GitHub, clone the project, open the folder in VS Code and run the app per the README. The goal is to change nothing until the project builds locally.',
    commands: ['git --version', 'git clone https://github.com/company/shop.git', 'cd shop', 'npm install', 'npm run dev'],
  },
  {
    title: 'Working on a task from GitHub Projects',
    role: 'Developer',
    body: 'They pick a card from the Ready column, assign themselves, branch off the latest main, make small commits and push the branch to GitHub.',
    commands: ['git checkout main', 'git pull --ff-only', 'git checkout -b feature/cart-empty-state', 'git add .', 'git commit -m "Add cart empty state"', 'git push -u origin feature/cart-empty-state'],
  },
  {
    title: 'Pull request and review',
    role: 'PR author + reviewer',
    body: 'The author describes context, attaches screenshots and links the issue. The reviewer checks behavior, tests and readability. Discussion happens in line-level comments.',
    commands: ['gh pr create --fill --base main', 'gh pr view --web', 'git commit -m "Address review comments"', 'git push'],
  },
  {
    title: 'Conflict while updating a PR',
    role: 'PR author',
    body: 'If main has moved on, the author pulls the changes, resolves the conflict in the VS Code Merge Editor, runs checks and re-pushes the branch.',
    commands: ['git fetch origin', 'git rebase origin/main', 'git status', 'npm test', 'git push --force-with-lease'],
  },
  {
    title: 'Urgent production hotfix',
    role: 'Team',
    body: 'Unfinished work is stashed, a hotfix branch is cut from main, the smallest possible fix is made, quickly reviewed and merged after checks pass.',
    commands: ['git stash push -m "wip before hotfix"', 'git checkout main', 'git pull --ff-only', 'git checkout -b hotfix/payment-timeout', 'git commit -m "Fix payment timeout handling"'],
  },
  {
    title: 'Tagged version release',
    role: 'Release manager',
    body: 'After all PRs land in main, the team creates a versioned tag, publishes a GitHub Release with notes, and GitHub Actions builds and ships the artifact.',
    commands: ['git checkout main', 'git pull --ff-only', 'git tag -a v1.4.0 -m "Release 1.4.0"', 'git push origin v1.4.0', 'gh release create v1.4.0 --generate-notes'],
  },
  {
    title: 'Working from a fork in open source',
    role: 'External contributor',
    body: 'They fork the repository into their account, add the original as upstream, regularly sync main and send PRs back to the original repository.',
    commands: ['git clone https://github.com/me/lib.git', 'git remote add upstream https://github.com/original/lib.git', 'git fetch upstream', 'git rebase upstream/main', 'git push --force-with-lease'],
  },
  {
    title: 'Multi-round review with fixup commits',
    role: 'PR author',
    body: 'Review changes are recorded as separate fixup commits so the reviewer can see each delta. Before merging, autosquash-rebase joins them into one neat commit.',
    commands: ['git commit --fixup HEAD', 'git push', 'git fetch origin', 'git rebase -i --autosquash origin/main', 'git push --force-with-lease'],
  },
  {
    title: 'Accidentally committed secret',
    role: 'Author + DevOps',
    body: 'If a token leaks into the repo, the secret is revoked at the provider first. Only then is the history scrubbed (git filter-repo / BFG), force-pushed, and the team notified.',
    commands: ['# 1. revoke the token in the provider dashboard ASAP', 'git filter-repo --path .env --invert-paths', 'git push origin --force --all', 'git push origin --force --tags'],
  },
] as const

export const extensionsEn = [
  ['GitHub Pull Requests', 'Work with PRs and issues right inside VS Code: check out PRs, comments, reviews, check statuses.'],
  ['GitLens', 'Line history, change authors, branch comparison, commit navigation.'],
  ['Git Graph', 'Visual graph of branches, merges, rebases and project history.'],
  ['GitHub Actions', 'View workflows, CI logs and build statuses.'],
  ['GitHub Repositories', 'Open repositories without a full clone \u2014 handy for quick reading and browsing.'],
  ['Project Manager', 'Quickly switch between several local projects.'],
  ['Conventional Commits', 'Suggests message formats (feat, fix, chore) and simplifies changelog generation.'],
  ['Code Spell Checker', 'Catches typos in commits, branch names and PR descriptions.'],
] as const

export const conceptsEn = [
  {
    id: 'git-vs-github',
    title: 'Git \u2260 GitHub',
    short: 'Two different things. People often mix them up.',
    analogy: 'Git is like Word, where you write a document. GitHub is like Google Drive, where you upload that document and others can read and comment on it. You can use Git without GitHub (locally only), but GitHub does not work without Git.',
    detail: 'Git is a program on your computer. It tracks file versions and works fully offline. GitHub is a hosted website. It takes a Git repository and adds a social layer on top: pull requests, issues, discussions, permissions, automated checks. Alternatives to GitHub: GitLab, Bitbucket, Gitea \u2014 all built on the same Git underneath.',
    practice: 'Install Git \u2192 verify with `git --version`. Sign up at github.com \u2192 create an empty repository. Two separate steps in two separate places.',
    pitfall: 'Saying "I committed it on GitHub" \u2014 no, commits happen locally. They land on GitHub only after `git push`.',
    viz: 'git-vs-github',
  },
  {
    id: 'repository',
    title: 'Repository (repo)',
    short: 'A project folder + a diary of every change.',
    analogy: 'Imagine a folder with project files. Inside it lives a tiny hidden folder `.git/` \u2014 the "diary". Git quietly writes there: who, when, which line they changed. You can flip back through the diary and return to any page.',
    detail: 'A repository is just a folder where `git init` or `git clone` was run. Inside, `.git/` appears with the full history. If you delete that folder \u2014 the files stay but the history and GitHub link are gone. If you delete the files but keep `.git/` \u2014 the history can be restored.',
    practice: '`git init my-project` \u2192 the folder becomes a repository. `ls -la` shows the .git directory inside.',
    pitfall: 'Copying a folder without `.git/` \u2014 that\u2019s no longer a repository, just files. To clone with history, use `git clone`, not "copy-paste".',
    viz: 'repository',
  },
  {
    id: 'commit',
    title: 'Commit',
    short: 'A save point of the project at a moment in time.',
    analogy: 'Like a save in a video game: "I want to be able to come back here". Except a Git save also stores who made it, when, and why (your commit message).',
    detail: 'A commit is a snapshot of all tracked files plus metadata (author, date, message, link to the parent commit). Each commit has a unique hash (e.g. `a1b2c3d`). Commits form a chain \u2014 that is the history. A good commit message answers "why this change", not "what I changed" (the diff already shows that).',
    practice: '`git add file.ts` \u2192 `git commit -m "feat: add login"`. A Conventional Commits style message (feat/fix/chore/docs) is automatically picked up by changelog generators.',
    pitfall: 'Committing a huge "everything I did this week" once a week. Better: small commits, one task each. History is easier to read and easier to roll back.',
    viz: 'commit',
  },
  {
    id: 'branch',
    title: 'Branch',
    short: 'A parallel universe of your project.',
    analogy: 'Imagine you are writing a book and want to try an alternate ending. You make a copy of the manuscript, experiment in the copy, and if it works \u2014 carry it back into the main one. If it does not \u2014 throw the copy away, the main is unharmed.',
    detail: 'A branch is just a pointer to a commit. Creating one is essentially free (no file copying). The main branch is usually called `main` (formerly `master`). All new work happens in separate feature branches so `main` always stays working. A finished branch is merged into `main` via a Pull Request.',
    practice: '`git switch -c feature/login` creates the branch and switches to it. `git switch main` \u2014 back to main. `git branch` \u2014 list all branches.',
    pitfall: 'Doing everything directly in `main`. Once teammates join, that branch becomes a soup of conflicts and half-finished work.',
    viz: 'branch',
  },
  {
    id: 'head',
    title: 'HEAD',
    short: 'A "you are here" bookmark.',
    analogy: 'In the book you are reading there is a bookmark. It shows the page you are on. HEAD is Git\u2019s bookmark: which commit and which branch you are currently on. When you make a new commit \u2014 the bookmark moves to it automatically.',
    detail: 'HEAD is a special pointer to "the current place". Usually HEAD points at a branch, and the branch points at the latest commit. After `git switch other-branch` HEAD moves to that branch. After `git checkout a1b2c3d` (a hash) HEAD points directly at a commit \u2014 a "detached HEAD". You can browse code there, but new commits will be lost if you do not create a branch.',
    practice: '`git log --oneline -5` shows the last few commits and marks where HEAD is.',
    pitfall: 'Committing in detached HEAD and switching back \u2014 commits "disappear" (but can be found via `git reflog`).',
    viz: 'head',
  },
  {
    id: 'remote',
    title: 'Remote and origin',
    short: 'The address of a copy of the repo in the cloud.',
    analogy: 'On your computer you have the working draft. On GitHub you have the "canonical" copy that the whole team uses. That copy is called a `remote`, and its default address is `origin`. Like "your parents\u2019 house": one of the places you regularly send photos to.',
    detail: '`origin` is just a conventional name for the remote repository. You can have several remotes (for example, `origin` for your fork and `upstream` for the original). Each remote stores a server URL. `git remote -v` lists every configured address.',
    practice: '`git remote -v` \u2192 you see the URL of your origin. `git remote add upstream https://github.com/org/orig.git` \u2014 add another one.',
    pitfall: 'Thinking that after `git commit` your teammates already see the changes. They do not \u2014 until you `git push`, the commit lives only on your machine.',
    viz: 'remote',
  },
  {
    id: 'clone-fetch-pull-push',
    title: 'clone, fetch, pull, push',
    short: '4 actions between your computer and GitHub.',
    analogy: 'Picture a cloud drive. **clone** \u2014 download the folder for the first time. **fetch** \u2014 see what is new there (without applying it locally yet). **pull** \u2014 see and apply at once. **push** \u2014 upload your changes. That\u2019s the only traffic between your computer and GitHub.',
    detail: 'clone is a one-time action \u2014 it creates a local repository. fetch is a safe command, it only updates remote info without touching your files. pull = fetch + merge (or fetch + rebase, if configured). push sends your commits to the server. If new commits appeared on the server, push will be rejected \u2014 you have to pull first.',
    practice: '`git clone <url>` \u2192 clone. Morning: `git pull` \u2192 grab the news. Evening: `git push` \u2192 send yours.',
    pitfall: 'Running `git pull` in the middle of half-finished work \u2014 Git may demand you commit or stash (`git stash`) the current edits first.',
    viz: 'clone-fetch-pull-push',
  },
  {
    id: 'merge-vs-rebase',
    title: 'merge vs rebase',
    short: 'Two ways to combine parallel branches.',
    analogy: '**merge** \u2014 like taping two pages together: both are visible, with a "seam" (the merge commit). **rebase** \u2014 rewrite the second page so it reads as if it followed the first one straight away: a single tidy page, but it is a reprint, not the original.',
    detail: 'merge takes two branches and creates a new merge commit. History is preserved as it was, but the graph is non-linear. rebase "moves" your commits to look as if you wrote them on top of the latest main. The history is linear and clean, but commits get new hashes \u2014 that is rewriting history. Rule of thumb: rebase only on your own local branches, before you push.',
    practice: 'Before opening a PR: `git fetch origin` \u2192 `git rebase origin/main` \u2192 linear history. After the rebase: `git push --force-with-lease`.',
    pitfall: 'Rebasing a branch your teammates use, then push --force \u2014 their history breaks. Never rebase shared branches.',
    viz: 'merge-vs-rebase',
  },
  {
    id: 'conflict',
    title: 'Merge conflict',
    short: 'Two people changed the same line \u2014 Git can\u2019t pick.',
    analogy: 'Two people edited the same paragraph in Google Docs but offline. When they try to merge their versions, the question pops up: "whose wins?". Only a human can answer.',
    detail: 'When Git can\u2019t merge changes automatically, it inserts markers `<<<<<<<`, `=======`, `>>>>>>>` into the file \u2014 with two variants between them. Your job: open the file, choose (or combine) the right one, remove the markers, `git add` the file, then `git commit` (if it was a merge) or `git rebase --continue` (if it was a rebase). VS Code highlights conflicts and offers "Accept Current / Incoming / Both" buttons.',
    practice: 'Create a conflict on purpose: change the same line in two branches. Run a merge \u2014 you\u2019ll see the markers and resolve them by hand.',
    pitfall: 'Committing a file with leftover `<<<<<<<` inside. The code won\u2019t compile, CI breaks, reviewers cry.',
    viz: 'conflict',
  },
  {
    id: 'pull-request',
    title: 'Pull Request (PR)',
    short: 'A request to "take my code into the main project".',
    analogy: 'You wrote an article for a magazine and sent it to the editors with a note: "please publish". The editors read it, leave notes, you revise, and eventually the article ships. A PR is the same thing for code.',
    detail: 'A PR is a page on GitHub comparing two branches: yours and the target one (usually `main`). It shows the file diff, line-by-line discussions, CI statuses, and a "Merge" button. A good PR is small (200\u2013400 lines) with a clear description following a "why / what / how to test" template.',
    practice: 'After pushing a new branch, GitHub offers "Compare & pull request". Or from VS Code: command "GitHub Pull Requests: Create Pull Request".',
    pitfall: 'A 3000-line PR with no description, mixing features and refactors. Nobody can review that properly.',
    viz: 'pull-request',
  },
  {
    id: 'code-review',
    title: 'Code Review',
    short: 'Teammates read your PR before merging.',
    analogy: 'A copy editor and editor read your article before publication. They highlight typos, awkward phrasing, suggest rewrites. Their goal isn\u2019t to humiliate you \u2014 it\u2019s to make the text better.',
    detail: 'A reviewer sees the diff, leaves comments on specific lines, and sets a status: Comment (just thoughts), Approve (good to merge), Request Changes (needs fixing). Good practice: the author asks 1\u20132 people for review, replies to each comment ("fixed" / "I disagree because\u2026"), doesn\u2019t take criticism personally.',
    practice: 'In VS Code open the PR via GitHub Pull Requests, click "Start Review", then click lines and leave notes.',
    pitfall: 'A reviewer writing "I don\u2019t like it" without explanation. Or the author getting offended and arguing for the sake of it. A healthy team discusses options, not personalities.',
    viz: 'code-review',
  },
  {
    id: 'ci-actions',
    title: 'CI and GitHub Actions',
    short: 'A robot that checks your code after every push.',
    analogy: 'Picture a robotic copy editor that reads every change you make and reports: "all good" or "error on page 3". It works 24/7, never tires, always checks the same way. CI is the idea, GitHub Actions is one specific implementation on GitHub.',
    detail: 'CI (Continuous Integration) is the practice of automatically building and testing code on every change. GitHub Actions is a built-in service that runs scenarios (workflows) from `.github/workflows/*.yml` files. Typical checks: tests, linter, build, dependency security. Branch rules can block merging until CI is green.',
    practice: 'Create `.github/workflows/ci.yml` with `npm ci` and `npm test` steps. Open a PR \u2014 the "Checks" status appears right inside it.',
    pitfall: 'Ignoring a failing CI "because it works on my machine". The cause is usually a different Node version or a missing environment variable.',
    viz: 'ci-actions',
  },
  {
    id: 'fork',
    title: 'Fork',
    short: 'Your personal copy of someone else\u2019s repo on GitHub.',
    analogy: 'You want to add a chapter to someone else\u2019s book but don\u2019t own it. You photocopy the whole book, add your chapter, then go to the author saying "please take my chapter into the original". The author decides.',
    detail: 'Fork is a button on a repo page. After clicking, a copy `myname/repo` appears under your account, which you can push to. To propose changes back to the original, you open a PR from your fork. Used in open source: you can\u2019t write to `facebook/react`, but you can fork it and send a PR. Also at work, when you don\u2019t have push rights to a protected branch.',
    practice: 'On any open-source repo page \u2014 the Fork button. Then `git clone <your-fork>`, edit, push, open a PR.',
    pitfall: 'You forked a year ago and forgot it. To sync: add `upstream` (the original) and regularly `git fetch upstream && git rebase upstream/main`.',
    viz: 'fork',
  },
] as const

export const tracksEn = [
  {
    id: 'solo',
    level: 'Level 1',
    emoji: '\uD83D\uDFE2',
    title: 'Solo developer',
    intro: 'The basic loop: create a project, keep history, push it to GitHub, recover from a mistake. Without this, going further is pointless.',
    exercises: [
      {
        title: 'Spin up your first repository from scratch',
        goal: 'Understand what a local repository is and how it links to GitHub.',
        steps: [
          'Create a folder `playground`, run `git init` inside',
          'Create `README.md` with one line of text',
          'Run `git add README.md`, then `git commit -m "init"`',
          'On GitHub create an empty repository with the same name',
          '`git remote add origin <url>` \u2192 `git push -u origin main`',
        ],
        done: 'The file is visible on the repository\u2019s GitHub page.',
      },
      {
        title: 'A series of meaningful commits',
        goal: 'Learn to slice work into small logical steps.',
        steps: [
          'Add 3 files: `index.html`, `style.css`, `script.js`',
          'Each file \u2014 a separate commit with a `feat: add ...` style message',
          'Run `git log --oneline` and make sure the history reads like an "instruction"',
        ],
        done: 'In `git log` you see 3 commits, each message clearly says what was done.',
      },
      {
        title: 'Work in a branch and merge it',
        goal: 'Understand why branches exist.',
        steps: [
          '`git switch -c feature/dark-mode`',
          'Make 2\u20133 changes and commit them',
          '`git switch main` \u2192 `git merge feature/dark-mode`',
          '`git branch -d feature/dark-mode` (delete locally)',
        ],
        done: 'In `git log --graph --oneline --all` you can see the branch and the merge.',
      },
      {
        title: 'Roll back accidental changes',
        goal: 'Stop being afraid to experiment \u2014 Git always has your back.',
        steps: [
          'Break code in a working file on purpose',
          'If you have not run `add` yet: `git restore <file>` \u2014 the file comes back',
          'If you have already added: `git restore --staged <file>` \u2192 then `git restore <file>`',
          'If you already committed: `git revert HEAD` creates an inverse commit',
        ],
        done: 'You understand the difference between restore, restore --staged, revert and reset.',
      },
      {
        title: 'Get back to an old version of a file',
        goal: 'Be able to pull a file out of history without touching the rest.',
        steps: [
          'Find the commit hash in `git log --oneline`',
          '`git show <hash>:path/to/file` \u2014 view the contents',
          '`git restore --source=<hash> path/to/file` \u2014 restore it',
        ],
        done: 'The file is rolled back to the right version, nothing else is affected.',
      },
      {
        title: 'Stash unfinished work',
        goal: 'Be able to temporarily set aside edits to handle something urgent.',
        steps: [
          'Make changes, do not commit',
          '`git stash push -m "wip dark mode"`',
          'Switch to another branch, do some work',
          'Come back: `git stash list` \u2192 `git stash pop`',
        ],
        done: 'Your edits are back in place, the stash is empty.',
      },
    ],
  },
  {
    id: 'opensource',
    level: 'Level 2',
    emoji: '\uD83D\uDFE1',
    title: 'Open source contributor',
    intro: 'How to propose a change to someone else\u2019s project, sync with the original and not get lost in forks.',
    exercises: [
      {
        title: 'Make your first PR to someone else\u2019s repo',
        goal: 'Walk the full cycle: fork \u2192 clone \u2192 branch \u2192 PR.',
        steps: [
          'Find a repo with the `good first issue` tag (e.g. via github.com/explore)',
          'Click Fork \u2014 you get a copy `myname/repo`',
          '`git clone git@github.com:myname/repo.git`',
          '`git switch -c fix/typo-in-readme`',
          'Make the change, commit, `git push -u origin fix/typo-in-readme`',
          'On GitHub click "Compare & pull request", fill in the description',
        ],
        done: 'The PR appears in the original repository with a number and Open status.',
      },
      {
        title: 'Hook up upstream and sync the fork',
        goal: 'Don\u2019t fall behind the original.',
        steps: [
          '`git remote add upstream <original url>`',
          '`git remote -v` \u2014 should show 2 remotes: origin (yours) and upstream',
          '`git fetch upstream`',
          '`git switch main` \u2192 `git rebase upstream/main`',
          '`git push --force-with-lease origin main`',
        ],
        done: '`git log --oneline` shows all the latest commits from the original.',
      },
      {
        title: 'Respond to maintainer feedback in your PR',
        goal: 'Understand iterative PR refinement.',
        steps: [
          'In the same feature branch, address the comments',
          'Commit: `git commit -m "review: rename variable"`',
          '`git push` \u2014 the PR updates automatically',
          'In the discussion answer each comment or click Resolve',
        ],
        done: 'All threads are Resolved, the PR is merged.',
      },
      {
        title: 'Sign commits with GPG/SSH',
        goal: 'Earn the Verified badge \u2014 required in many open-source projects.',
        steps: [
          'Generate an SSH signing key: `ssh-keygen -t ed25519 -f ~/.ssh/sign`',
          'In GitHub Settings \u2192 SSH and GPG keys \u2192 add the key as Signing key',
          '`git config --global gpg.format ssh`',
          '`git config --global user.signingkey ~/.ssh/sign.pub`',
          '`git config --global commit.gpgsign true`',
        ],
        done: 'New commits on GitHub are marked with a Verified badge.',
      },
      {
        title: 'Find and accept someone else\u2019s PR in your project',
        goal: 'Try being the maintainer.',
        steps: [
          'Open a teammate\u2019s PR in your repository',
          'In VS Code: GitHub Pull Requests \u2192 Checkout PR',
          'Run the project locally, test it',
          'Leave 2\u20133 line comments, then Approve and Merge',
        ],
        done: 'The PR is merged and the branch was deleted automatically.',
      },
    ],
  },
  {
    id: 'team',
    level: 'Level 3',
    emoji: '\uD83D\uDFE0',
    title: 'Team member',
    intro: 'Daily work in a team of 3+ people: branches, reviews, conflicts, releases. This is where "confident user" begins.',
    exercises: [
      {
        title: 'Work the trunk-based way',
        goal: 'Master the simplest, safest branching approach.',
        steps: [
          'Morning: `git switch main` \u2192 `git pull --rebase`',
          '`git switch -c feature/my-task`',
          'Small commits throughout the day',
          'Before opening the PR: `git fetch origin` \u2192 `git rebase origin/main`',
          'Open the PR, wait for green CI and approve, hit Merge',
        ],
        done: 'The branch lives less than 2 days, the PR stays under 400 lines.',
      },
      {
        title: 'Resolve a real merge conflict',
        goal: 'Stop panicking when you see `<<<<<<<`.',
        steps: [
          'Create two branches off main, change the same line in both',
          'Merge the first into main, then try to rebase the second onto main',
          'Open the file with conflicts in VS Code \u2014 use "Accept Current/Incoming/Both"',
          '`git add <file>` \u2192 `git rebase --continue`',
          'Run tests, make sure the code works',
        ],
        done: 'The conflict is resolved, CI is green, no `<<<` markers in the files.',
      },
      {
        title: 'Make stacked PRs',
        goal: 'Learn to break a big task into a chain of smaller PRs.',
        steps: [
          'From main: `git switch -c refactor/extract-api`',
          'Refactor and open a PR into main',
          'From the same branch: `git switch -c feature/profile-page`',
          'Build the feature, open a PR into `refactor/extract-api`',
          'After the first one merges \u2014 GitHub auto-rebases the second\u2019s base to main',
        ],
        done: 'Two open PRs, the second waiting for the first to merge.',
      },
      {
        title: 'Review a teammate\u2019s PR',
        goal: 'Learn to give constructive feedback.',
        steps: [
          'Open the PR, switch to the branch via GitHub Pull Requests in VS Code',
          'Read the PR description, understand the task',
          'Walk through the diff: look for unclear bits, potential bugs, missing tests',
          'For each note \u2014 a concrete suggestion, not "I don\u2019t like it"',
          'Set Approve / Request changes / Comment',
        ],
        done: 'The author addressed your comments, the PR improved before merge.',
      },
      {
        title: 'Roll back a bad commit from main',
        goal: 'Be able to restore prod quickly.',
        steps: [
          'In `git log --oneline -10` find the problematic merge commit',
          '`git revert -m 1 <merge-hash>` \u2014 creates the inverse commit',
          '`git push origin main`',
          'Open a hotfix branch, fix the issue, new PR',
        ],
        done: 'main works again, history shows both the breakage and the revert.',
      },
      {
        title: 'Use draft PRs for early feedback',
        goal: 'Get architecture review before you write 1000 lines.',
        steps: [
          'After 1\u20132 commits with a rough implementation, open the PR as Draft',
          'In the description ask: "did I read the task right?", "is this the right approach?"',
          'Get feedback, iterate',
          'When ready \u2014 click "Ready for review"',
        ],
        done: 'The PR went through Draft and merged without major rewrites.',
      },
      {
        title: 'Protect main with branch protection',
        goal: 'Guarantee no code lands in main without review and green CI.',
        steps: [
          'Settings \u2192 Branches \u2192 Add rule for `main`',
          'Enable: Require pull request, Require approvals (1+), Require status checks',
          'Pick a CI check (e.g. build + test)',
          'Enable: Require linear history, Do not allow bypassing',
        ],
        done: 'Direct push to main is rejected, PRs without approval don\u2019t merge.',
      },
      {
        title: 'Set up CODEOWNERS',
        goal: 'Auto-assign reviewers based on code areas.',
        steps: [
          'Create file `.github/CODEOWNERS`',
          'Example: `/backend/ @backend-team` and `*.tsx @frontend-team`',
          'Commit it to main',
          'Open a PR with backend changes \u2014 GitHub will request review from @backend-team',
        ],
        done: 'The PR shows "Required reviewers from CODEOWNERS".',
      },
      {
        title: 'Use `git bisect` to find a bug',
        goal: 'Find a regression between two releases.',
        steps: [
          '`git bisect start`',
          '`git bisect bad` (current is broken) \u2192 `git bisect good v1.4.0` (working one)',
          'Git checks out a commit in the middle \u2014 run the test or check manually',
          'Mark `git bisect good` or `bad` \u2014 Git keeps splitting',
          'Eventually Git points at "first bad commit". `git bisect reset`',
        ],
        done: 'You found the exact commit that introduced the bug.',
      },
    ],
  },
  {
    id: 'maintainer',
    level: 'Level 4',
    emoji: '\uD83D\uDD34',
    title: 'Maintainer / tech lead',
    intro: 'Running a repository: automation, releases, security, templates for the team. This is the advanced GitHub user territory.',
    exercises: [
      {
        title: 'Set up issue and PR templates',
        goal: 'Standardize how requests and PRs are described.',
        steps: [
          'Create `.github/ISSUE_TEMPLATE/bug.yml` and `feature.yml` (YAML with fields)',
          'Create `.github/pull_request_template.md` with sections: "What", "Why", "How to test", "Checklist"',
          'Commit to main',
          'Create a new issue \u2014 the template picker appears',
        ],
        done: 'All new issues/PRs follow a single format.',
      },
      {
        title: 'Launch your first CI workflow',
        goal: 'Automate tests and lint.',
        steps: [
          '`.github/workflows/ci.yml` with trigger `on: [push, pull_request]`',
          'Steps: `actions/checkout@v4`, `actions/setup-node@v4`, `npm ci`, `npm test`',
          'Commit, open a PR \u2014 you see the Checks status',
          'In branch protection make this check required',
        ],
        done: 'PRs without green CI cannot be merged.',
      },
      {
        title: 'Ship a release with a changelog',
        goal: 'Use GitHub Releases for versioning.',
        steps: [
          '`git tag -a v1.0.0 -m "First stable"` \u2192 `git push origin v1.0.0`',
          'On GitHub \u2192 Releases \u2192 Draft a new release \u2192 pick the tag',
          'Click "Generate release notes" \u2014 GitHub assembles a changelog from PRs',
          'Publish',
        ],
        done: 'The release shows under Releases with downloadable archives.',
      },
      {
        title: 'Automatic deploy via Actions',
        goal: 'After merge to main, the code ships to staging/prod by itself.',
        steps: [
          'Workflow with trigger `on: push: branches: [main]`',
          'Steps: build \u2192 upload artifact \u2192 deploy (e.g. via actions/deploy-pages or vercel)',
          'Secrets (tokens, keys) live in Settings \u2192 Secrets and variables \u2192 Actions',
          'Use them in the workflow: `${{ secrets.DEPLOY_TOKEN }}`',
        ],
        done: 'A merge into main automatically updates the environment.',
      },
      {
        title: 'Enable Dependabot and security alerts',
        goal: 'Get PRs that update vulnerable dependencies.',
        steps: [
          'Settings \u2192 Code security and analysis \u2192 enable Dependabot alerts and version updates',
          'Create `.github/dependabot.yml` with a weekly schedule',
          'Wait for automated PRs from dependabot[bot]',
        ],
        done: 'Pull Requests now contain PRs from Dependabot.',
      },
      {
        title: 'Set up secret scanning and push protection',
        goal: 'Stop the team from leaking tokens into the repo.',
        steps: [
          'Settings \u2192 Code security \u2192 enable Secret scanning + Push protection',
          'Try to commit a test AWS key on purpose \u2014 the push will be rejected',
          'If a leak made it into history \u2014 `git filter-repo --invert-paths --path .env`',
        ],
        done: 'Pushes that contain a potential secret are blocked automatically.',
      },
      {
        title: 'Create a GitHub Project for the team',
        goal: 'See all the work on one board.',
        steps: [
          'Projects \u2192 New project \u2192 pick Board or Table',
          'Link it to a repository, add fields: Status, Priority, Sprint',
          'Enable automation: when a PR opens \u2192 In Review, when it merges \u2192 Done',
        ],
        done: 'The team works off the board, statuses update themselves.',
      },
    ],
  },
] as const

export const casesEn = [
  {
    icon: '\uD83D\uDD11',
    title: 'Committed .env with passwords',
    problem: 'A PR is already open and API keys are visible in history. Reset is pointless \u2014 the secret is already on GitHub.',
    solution: 'Revoke the token at the provider immediately, add .env to .gitignore, scrub history and force-push the branch. Warn the team: they will need to re-clone the repo.',
    commands: ['echo .env >> .gitignore', 'git rm --cached .env', 'git commit -m "Stop tracking .env"', 'git filter-repo --path .env --invert-paths', 'git push origin --force --all'],
    tag: 'security',
    viz: 'secret-leak',
  },
  {
    icon: '\u26A0\uFE0F',
    title: 'Committed to the wrong branch',
    problem: 'You spent half an hour coding in main instead of a feature branch. Push has not happened yet.',
    solution: 'Create a new branch from the current state, then reset main back to origin/main. Steps are safe as long as nothing is pushed.',
    commands: ['git switch -c feature/oops', 'git switch main', 'git reset --hard origin/main', 'git switch feature/oops'],
    tag: 'oops',
    viz: 'wrong-branch',
  },
  {
    icon: '\uD83D\uDD04',
    title: 'rebase broke the branch',
    problem: 'After git rebase -i the history looks weird and commits seem to be gone.',
    solution: 'Inspect reflog and reset the branch to the state before the rebase using a hash. Reflog keeps almost every move of HEAD.',
    commands: ['git reflog', 'git reset --hard HEAD@{5}'],
    tag: 'oops',
    viz: 'rebase-broken',
  },
  {
    icon: '\uD83E\uDDF9',
    title: 'Deleted a branch you actually needed',
    problem: 'After git branch -D the branch is gone, but it had code you still needed.',
    solution: 'Find the branch\u2019s last commit in reflog and recreate the branch from that hash.',
    commands: ['git reflog', 'git branch feature/login a1b2c3d', 'git switch feature/login'],
    tag: 'oops',
    viz: 'deleted-branch',
  },
  {
    icon: '\uD83D\uDCC4',
    title: 'Need to remove a file from the previous commit',
    problem: 'Something extra slipped into the last commit: a big binary or a temp file.',
    solution: 'Delete the file, add it to .gitignore and rewrite the last commit via amend.',
    commands: ['git rm --cached build.zip', 'echo build.zip >> .gitignore', 'git add .gitignore', 'git commit --amend --no-edit', 'git push --force-with-lease'],
    tag: 'oops',
    viz: 'wrong-file',
  },
  {
    icon: '\u26D4',
    title: 'A teammate force-pushed to your branch',
    problem: 'Your local commits diverge from origin and push gets rejected.',
    solution: 'No --force from your side. Make a safety branch, take the version from origin, then cherry-pick your commits across by hand. Talk to the team.',
    commands: ['git branch backup-mywork', 'git fetch origin', 'git reset --hard origin/feature/x', 'git cherry-pick backup-mywork~2..backup-mywork'],
    tag: 'team',
    viz: 'force-push',
  },
  {
    icon: '\uD83E\uDD1D',
    title: 'PR grew huge and nobody wants to review it',
    problem: '300+ files, refactor and a new feature mixed together.',
    solution: 'Split into stacked PRs: extract the refactor into its own branch, build the feature on top of it. PRs of 200\u2013400 lines each are reviewed several times faster.',
    commands: ['git switch -c refactor/extract-api main', 'git cherry-pick <refactor commits>', 'gh pr create --base main --title "Refactor API layer"', 'git switch -c feature/profile refactor/extract-api'],
    tag: 'team',
    viz: 'big-pr',
  },
  {
    icon: '\uD83D\uDCE6',
    title: 'Big binary files in the repository',
    problem: 'Videos, PSDs and datasets blow the clone up to several GB.',
    solution: 'Set up Git LFS, declare file patterns and commit .gitattributes. Use git filter-repo to evict old binaries from history.',
    commands: ['git lfs install', 'git lfs track "*.psd"', 'git add .gitattributes', 'git add design/hero.psd', 'git commit -m "Move design assets to LFS"'],
    tag: 'release',
    viz: 'lfs',
  },
  {
    icon: '\uD83D\uDD0D',
    title: 'Unclear when a test broke',
    problem: 'A test fails in prod but passed in the previous version. Hundreds of commits in between.',
    solution: 'Use git bisect: Git binary-searches for the commit that introduced the bug. At each step run the test and mark good/bad.',
    commands: ['git bisect start', 'git bisect bad', 'git bisect good v1.3.0', 'npm test', 'git bisect good   # or bad', 'git bisect reset'],
    tag: 'history',
    viz: 'bisect',
  },
  {
    icon: '\u23EA',
    title: 'Need to roll back a release in prod',
    problem: 'A release shipped and users are complaining. You need to revert quickly.',
    solution: 'Never rewrite main\u2019s history. Revert the PR\u2019s merge commit or roll the release back via GitHub Releases. Then ship a hotfix.',
    commands: ['git revert -m 1 <merge-commit>', 'git push origin main', 'gh release edit v1.4.0 --draft'],
    tag: 'release',
    viz: 'rollback',
  },
  {
    icon: '\u270D\uFE0F',
    title: 'Wrong author on a commit',
    problem: 'A commit went out under a teammate\u2019s work email or with a personal name instead of the work one.',
    solution: 'Set the right author on the last commit or just configure a per-project user.email up front.',
    commands: ['git config user.email "work@company.com"', 'git commit --amend --author="Ivan <work@company.com>" --no-edit', 'git push --force-with-lease'],
    tag: 'oops',
    viz: 'wrong-author',
  },
  {
    icon: '\uD83C\uDF10',
    title: 'CI is red but everything is green locally',
    problem: 'GitHub Actions fails on your branch and you can\u2019t reproduce it locally.',
    solution: 'Open the Actions tab on the PR and read the failed step\u2019s log. Compare Node version, env variables, time zones. Often it\u2019s enough to align Node with .nvmrc.',
    commands: ['gh run list --branch feature/x', 'gh run view <id> --log-failed', 'node -v   # compare with actions/setup-node in .github/workflows'],
    tag: 'team',
    viz: 'ci-mismatch',
  },
  {
    icon: '\uD83D\uDD17',
    title: 'Switching from HTTPS to SSH',
    problem: 'GitHub keeps asking for a password, or your org requires SSH.',
    solution: 'Generate an ed25519 key, add the public part to GitHub Settings, switch origin to the SSH URL. Verify with ssh -T git@github.com.',
    commands: ['ssh-keygen -t ed25519 -C "work@company.com"', 'cat ~/.ssh/id_ed25519.pub', 'gh ssh-key add ~/.ssh/id_ed25519.pub --title "work-laptop"', 'git remote set-url origin git@github.com:org/repo.git'],
    tag: 'security',
    viz: 'ssh',
  },
  {
    icon: '\uD83D\uDCDD',
    title: 'Need to rewrite the last few commit messages',
    problem: 'Commits are titled "fix", "asdf", "another fix". The PR history is unreadable.',
    solution: 'Interactive rebase lets you reword or squash commits. Build a logical history, then force-push with lease.',
    commands: ['git rebase -i origin/main', '# in the editor, change pick to reword/squash', 'git push --force-with-lease'],
    tag: 'history',
    viz: 'rewrite',
  },
  {
    icon: '\uD83C\uDF01',
    title: 'CRLF vs LF on Windows',
    problem: 'Diffs show the entire file as changed even though nobody touched it. The cause: line endings.',
    solution: 'Add .gitattributes, set core.autocrlf consistently across the team. Agree to always store LF in the repository.',
    commands: ['echo "* text=auto eol=lf" > .gitattributes', 'git config --global core.autocrlf input', 'git add --renormalize .', 'git commit -m "Normalize line endings"'],
    tag: 'team',
    viz: 'crlf',
  },
  {
    icon: '\uD83D\uDCC1',
    title: 'Submodule is stale or empty',
    problem: 'After cloning, the submodule folder is empty and the build breaks.',
    solution: 'Initialize the submodules and update them to the right commits. For future clones add --recurse-submodules.',
    commands: ['git submodule update --init --recursive', 'git submodule foreach git pull origin main'],
    tag: 'team',
    viz: 'submodule',
  },
  {
    icon: '\uD83E\uDDF9',
    title: 'Stale remote-tracking branches cluttering the list',
    problem: 'After merging a dozen PRs, the branches are deleted on GitHub, but git branch -r still shows origin/feature-xxx. It\u2019s unclear which branches are actually active.',
    solution: 'Run git fetch --prune \u2014 it removes all remote-tracking refs that no longer exist on the server. To make this automatic on every fetch/pull, set the global fetch.prune option. Delete leftover local branches separately with git branch -d.',
    commands: ['git fetch --prune', 'git config --global fetch.prune true', 'git branch -d feature/login'],
    tag: 'team',
    viz: 'prune',
  },
] as const

export const strategiesEn = [
  {
    name: 'Merge commit',
    summary: 'Creates a separate merge commit and keeps every PR commit as is.',
    when: 'The team wants to see how the work on a feature actually went.',
    pros: ['Preserves the full history', 'Rewrites nothing', 'Review history stays clear'],
    cons: ['Lots of noise in git log', 'Non-linear history graph'],
  },
  {
    name: 'Squash and merge',
    summary: 'Squashes all PR commits into one and adds it to main.',
    when: 'The team wants linear history, 1 PR = 1 commit.',
    pros: ['Clean linear main', 'Easy to revert a feature', 'WIP commits are hidden'],
    cons: ['Step-by-step history is lost', 'Authorship collapses to one person'],
  },
  {
    name: 'Rebase and merge',
    summary: 'Rebases the PR commits on top of main without a merge commit.',
    when: 'The team wants linear history but keeps every commit.',
    pros: ['Perfectly linear graph', 'Commits stay separate', 'Easy to bisect for bugs'],
    cons: ['Author has to keep the branch clean', 'Conflicts are resolved step by step', 'Commit hashes change'],
  },
] as const

export const safetyTipsEn: [string, string][] = [
  ['.gitignore from the very first commit', 'Add .env, node_modules, dist, *.log, .vscode/ before the first push. Templates: github.com/github/gitignore.'],
  ['Branch protection rules', 'Protect main: required reviews, required status checks, no force-push. No green CI \u2014 no merge.'],
  ['CODEOWNERS', 'A `.github/CODEOWNERS` file auto-assigns a reviewer based on file path. Useful in larger projects.'],
  ['Secret scanning', 'GitHub catches token leaks for you. Enable push protection \u2014 it blocks pushes that contain a secret.'],
  ['Dependabot', 'Automatically opens PRs with vulnerable-dependency updates and refreshes libs weekly.'],
  ['Signed commits', 'GPG or SSH signing proves authorship. The Verified badge appears on GitHub.'],
]

export const glossaryEn = [
  { term: 'Repository (repo)', definition: 'A project folder + a hidden `.git/` folder with a diary of every change. Analogy: a project folder with a built-in time machine.' },
  { term: 'Commit', definition: 'A snapshot of every file at a moment in time + author + message. Analogy: a save in a video game.' },
  { term: 'Branch', definition: 'A parallel line of development. Really just a pointer to a commit. Branches are free in Git \u2014 make a new one for every task.' },
  { term: 'main / master', definition: 'The main project branch. Used to be called master, now mostly main. Only finished, reviewed code lands here.' },
  { term: 'Remote', definition: 'A remote copy of the repository, usually on GitHub. push and pull talk specifically to the remote.' },
  { term: 'origin', definition: 'The default name for the primary remote. After `git clone` it is created automatically.' },
  { term: 'upstream', definition: 'Conventional name for the original repository you forked from. Used to sync with the original.' },
  { term: 'clone', definition: 'Download the entire repository (with history) onto your computer for the first time.' },
  { term: 'fetch', definition: 'Find out what is new on the remote without applying it to your files. A safe command \u2014 it breaks nothing.' },
  { term: 'pull', definition: 'fetch + automatic merge into your current branch. The morning "grab all the news" command.' },
  { term: 'push', definition: 'Send your local commits to the remote. Until you push, nobody else can see your changes.' },
  { term: 'Pull Request (PR / MR)', definition: 'A request to "take my code into the main branch". On GitLab it is called Merge Request \u2014 same thing.' },
  { term: 'Draft PR', definition: 'A draft PR. Visible to the team, open for discussion, but not yet ready to merge. Useful for early feedback.' },
  { term: 'Code review', definition: 'Reading and discussing a PR with teammates before merging. The goal: find issues and share knowledge, not humiliate the author.' },
  { term: 'Approve / Request changes', definition: 'The two main reviewer verdicts. Approve = "good to merge", Request changes = "needs fixes".' },
  { term: 'Fork', definition: 'A personal copy of someone else\u2019s repository on GitHub. Used to propose changes to a project where you don\u2019t have write access.' },
  { term: 'Merge', definition: 'Combining two branches. Git creates a "merge commit" with two parents. History is preserved as-is.' },
  { term: 'Rebase', definition: 'Replays your commits on top of another branch. The history becomes linear, but commits get new hashes (it is a rewrite).' },
  { term: 'Squash', definition: 'Combine several commits into one. Often applied at PR merge so main keeps one tidy commit per feature.' },
  { term: 'Cherry-pick', definition: 'Copy a specific commit from one branch to another. Handy for hotfixes in release branches.' },
  { term: 'Revert', definition: 'Create a new commit that undoes an old one. Safe for shared branches \u2014 history is not rewritten.' },
  { term: 'Reset', definition: 'Move HEAD to another commit. `--soft` keeps files, `--hard` wipes everything. A dangerous command \u2014 it rewrites history.' },
  { term: 'reflog', definition: 'A history of HEAD movements over the last 90 days. Saves you from almost any "I broke everything": gives hashes you can return to.' },
  { term: 'Stash', definition: 'A temporary "pocket" for uncommitted changes. Put them away (`stash push`), do something else, get them back (`stash pop`).' },
  { term: 'HEAD', definition: 'A "you are here" bookmark. Points to the current commit, usually via the current branch.' },
  { term: 'Detached HEAD', definition: 'HEAD points directly at a commit, not a branch. New commits in this state "hang in the air" \u2014 they can be lost after switching away.' },
  { term: 'Tag', definition: 'An immutable label on a commit. Usually for releases: `v1.0.0`, `v2.3.1`. GitHub builds Releases from tags.' },
  { term: 'Release', definition: 'A GitHub page bound to a tag. Contains the changelog, downloadable archives and binaries.' },
  { term: 'Conflict', definition: 'Two people changed the same line. Git inserts `<<<`/`===`/`>>>` markers \u2014 you must pick the right variant by hand.' },
  { term: 'CI', definition: 'Continuous Integration \u2014 automatic build and test on every push. On GitHub it is GitHub Actions.' },
  { term: 'GitHub Actions', definition: 'GitHub\u2019s built-in automation service. Scenarios live in `.github/workflows/*.yml`. Every account has free minutes.' },
  { term: 'Workflow', definition: 'A YAML file describing automation: when to run, on what, with which steps. A repo can have several workflows.' },
  { term: 'Runner', definition: 'A server that executes a workflow. GitHub provides free runners (Linux/Windows/macOS); you can also host your own.' },
  { term: 'Secret', definition: 'A safe storage for tokens and keys in repository settings. Available in workflows as `${{ secrets.NAME }}` and never shown in logs.' },
  { term: 'Issue', definition: 'A task, bug or idea in GitHub\u2019s tracker. Reference by number (`#42`), link to PRs, group into projects.' },
  { term: 'Label', definition: 'A coloured tag on an issue/PR: `bug`, `feature`, `good first issue`. Helps with filtering.' },
  { term: 'Milestone', definition: 'A group of issues/PRs sharing a common goal or date (e.g. "Release v2.0"). Tracks progress.' },
  { term: 'Project (board)', definition: 'A Kanban board or table for managing tasks. Cards can change status automatically based on events.' },
  { term: 'Branch protection', definition: 'Rules for branches: ban direct pushes, require approved PRs, require green CI, protect against force-push.' },
  { term: 'CODEOWNERS', definition: 'A `.github/CODEOWNERS` file declaring who is responsible for which parts of the code. GitHub auto-assigns reviewers in PRs.' },
  { term: '.gitignore', definition: 'A list of paths Git should ignore (`node_modules/`, `.env`, `dist/`). Without it the repo fills up with junk.' },
  { term: '.gitattributes', definition: 'File handling settings: line endings (eol), binary-ness, filters. Most importantly \u2014 unified line endings across the team.' },
  { term: 'SSH key', definition: 'A pair of crypto keys for password-less authentication. Public goes to GitHub, private stays with you. Modern choice: ed25519.' },
  { term: 'Personal Access Token (PAT)', definition: 'A token instead of a password for HTTPS operations and the API. Created in Settings \u2192 Developer settings.' },
  { term: 'Force-push', definition: 'Overwrites the remote\u2019s history. Dangerous on shared branches \u2014 teammates\u2019 history breaks.' },
  { term: 'Force-with-lease', definition: 'A safe variant of force-push: it aborts if there are commits on the remote you don\u2019t have.' },
  { term: 'Submodule', definition: 'A repository inside a repository, pinned to a specific commit. Convenient for shared libraries, but requires `--recurse-submodules`.' },
  { term: 'LFS (Large File Storage)', definition: 'A Git extension for large binary files: the repo stores only a pointer, the file itself lives on a separate server.' },
  { term: 'Monorepo', definition: 'Several projects in a single repository. Convenient for shared CI and code reuse, but takes setup.' },
  { term: 'Trunk-based', definition: 'A strategy: one main branch `main`, short-lived feature branches (1\u20132 days), frequent merges. Minimal conflicts.' },
  { term: 'Git Flow', definition: 'An older strategy with develop, release and hotfix branches. More complex than most projects need.' },
  { term: 'gh CLI', definition: 'GitHub\u2019s official terminal tool. Opens PRs, inspects CI, downloads releases \u2014 all without a browser.' },
  { term: 'Conventional Commits', definition: 'A message format: `feat:`, `fix:`, `chore:`, `docs:`. Drives changelog generation and version bumps.' },
  { term: 'Dependabot', definition: 'A GitHub bot that opens PRs with updates for vulnerable dependencies. Enabled in Settings \u2192 Code security.' },
  { term: 'Secret scanning', definition: 'Automatic search for tokens and keys in code. Push protection blocks a commit with a secret before it can be pushed.' },
]
